---
- hosts: KUSMFG-SW06
  gather_facts: false
  connection: local
  vars_files:
    - /root/ansibleCRED/cred.yml
  
  tasks:      
    - name: send configuration commands to Switch
      telnet:
        user: "{{ cred.username }}"
        password: "{{ cred.password }}"
        login_prompt: "Username: "
        pause: 1
        prompts:
          - "[#]"
        command:
          - configure terminal
          - interface Gi1/0/37
          - shut
          - shut
          - shut
          - no shut
          - interface Gi1/0/17
          - shut
          - shut
          - shut
          - no shut
          - interface Gi1/0/3
          - shut
          - shut
          - shut
          - no shut
          - interface Gi1/0/7
          - shut
          - shut
          - shut
          - no shut
          - interface Gi1/0/10
          - shut
          - shut
          - shut
          - no shut
          - interface Gi1/0/44
          - shut
          - shut
          - shut
          - no shut
          - end
          - exit