---
- hosts: shachpmt-sw-cr26
  gather_facts: false
  connection: local
  vars_files:
    - /root/ansibleCRED/cred.yml
  
  tasks:      
    - name: send configuration commands to Switch
      telnet:
        user: "{{ cred.username }}"
        password: "{{ cred.password }}"
        login_prompt: "Username: "
        pause: 1
        prompts:
          - "[#]"
        command:
          - configure terminal
          - interface Gi0/30
          - shut
          - shut
          - shut
          - no shut
          - interface Gi0/29
          - shut
          - shut
          - shut
          - no shut
          - interface Gi0/18
          - shut
          - shut
          - shut
          - no shut
          - interface Gi0/45
          - shut
          - shut
          - shut
          - no shut
          - interface Gi0/2
          - shut
          - shut
          - shut
          - no shut
          - interface Gi0/44
          - shut
          - shut
          - shut
          - no shut
          - end
          - exit